# PyTorch Tensor Manipulations

In [1]:
import torch

## Tensor Shaping

### reshape: Change Tensor Shape

In [2]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

print(x.size())

torch.Size([3, 2, 2])


![image](https://user-images.githubusercontent.com/105966480/209546654-ffba5f4d-c67a-41eb-924b-63f7203b85f4.png)

In [3]:
print(x.reshape(12)) # 12 = 3 * 2 * 2
print(x.reshape(-1))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [4]:
print(x.reshape(3, 4)) # 3 * 4 = 3 * 2 * 2
print(x.reshape(3, -1))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


![image](https://user-images.githubusercontent.com/105966480/209546857-64ba8de8-88aa-4cac-b2df-40292043dc40.png)

In [5]:
print(x.reshape(3, 1, 4))
print(x.reshape(-1, 1, 4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


![image](https://user-images.githubusercontent.com/105966480/209546993-cea9b470-0dee-4503-96a9-40cc999df1b1.png)

In [6]:
print(x.reshape(3, 2, 2, 1))
# contiguous + 'view' = reshape
# contiguous - 메모리에서 분리 된 상태를 연결

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


You can use 'view()' instead of 'reshape()' in some cases.

- https://pytorch.org/docs/stable/tensor_view.html
- https://pytorch.org/docs/stable/tensors.html?highlight=view#torch.Tensor.view

### squeeze: Remove dimension which has only one element.

In [7]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]]])
print(x.size())

torch.Size([1, 2, 2])


Remove any dimension which has only one element.

In [8]:
print(x.squeeze())
print(x.squeeze().size())
# 여기서 한 번 더 squeeze하더라도, 같은 Size가 반환 됨.

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


Remove certain dimension, if it has only one element.
If it is not, there would be no change.

In [9]:
print(x.squeeze(0).size()) # 0번 인덱스 -> squeeze가 되었음
print(x.squeeze(1).size()) # 1번 인덱스 -> squeeze가 되지 않음

torch.Size([2, 2])
torch.Size([1, 2, 2])


### unsqueeze: Insert dimension at certain index.

- 항상 어떤 dimension을 unsqueeze할지 설정해줘야 함

In [10]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
print(x.size())

torch.Size([2, 2])


In [11]:
print(x.unsqueeze(2)) #[2,2,1]
print(x.unsqueeze(-1)) #[2,2,1]
print(x.reshape(2, 2, -1)) #[2,2,1]

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
