# PyTorch Tensor Operations

In [1]:
import torch

## Arithmetic Element-wise Operations

- 사칙연산

In [2]:
a = torch.FloatTensor([[1, 2],
                       [3, 4]])
b = torch.FloatTensor([[2, 2],
                       [3, 3]])

In [3]:
a + b

tensor([[3., 4.],
        [6., 7.]])

In [4]:
a - b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [5]:
a * b

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [6]:
a / b

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

- 논리 연산

In [7]:
a == b

tensor([[False,  True],
        [ True, False]])

In [8]:
a != b

tensor([[ True, False],
        [False,  True]])

- 제곱근

In [9]:
a ** b

tensor([[ 1.,  4.],
        [27., 64.]])

- 이렇게 연산을 하면서, back-propagation을 준비한다

## Inplace Operations

- mul - 매번 새로운 메모리를 할당하고, 그 자리에서 연산
- ☆ Inplace Operations
    - mul_ - 선언된 메모리를 할당하고, 그 자리를 덮어 씌움 = 주소를 그대로 사용
    - 메모리적으로 과연 더 효율적일까?
        - PyTorch 내부에 옵티마이저가 잘 되어 있기 때문에, 속도적인 측면에서 차이 X

In [10]:
print(a)
print(a.mul(b))
print(a)
print(a.mul_(b))
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


## Sum, Mean (Dimension Reducing Operations)

In [11]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

In [12]:
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


- 특정 차원만 연산하고 싶은 경우

In [13]:
print(x.sum(dim=0))
print(x.sum(dim=-1))

tensor([4., 6.])
tensor([3., 7.])


![image](https://user-images.githubusercontent.com/105966480/209473205-41f875ad-e0a4-46a4-9c1b-c9aec34d61cd.png)

---
![image](https://user-images.githubusercontent.com/105966480/209473220-d35eaa51-2383-45ee-a7af-503fb065ea80.png)

## Broadcast in Operations

- 모양이 다른 텐서 간의 연산을 할 때
- 오류가 있더라도, 자체적으로 연산 진행

What we did before,

In [14]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[4, 8]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([1, 2])


In [15]:
z = x + y
print(z)
print(z.size())

tensor([[ 5., 10.]])
torch.Size([1, 2])


Broadcast feature provides operations between different shape of tensors.

### Tensor + Scalar

In [16]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
y = 1

print(x.size())

torch.Size([2, 2])


In [17]:
z = x + y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


### Tensor + Vector

In [18]:
x = torch.FloatTensor([[1, 2],
                       [4, 8]])
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

torch.Size([2, 2])
torch.Size([2])


![image](https://user-images.githubusercontent.com/105966480/209473466-5e05f6d9-bcc0-40fb-8cc2-f7b6cfa1c073.png)

In [19]:
z = x + y
print(z)
print(z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


![image](https://user-images.githubusercontent.com/105966480/209473524-88e76443-9df1-4749-a191-ebae8b8e3a0f.png)

In [20]:
x = torch.FloatTensor([[[1, 2]]])
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

torch.Size([1, 1, 2])
torch.Size([2])


In [21]:
z = x + y
print(z)
print(z.size())

tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


### Tensor + Tensor

In [22]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3],
                       [5]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [23]:
z = x + y
print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


![image](https://user-images.githubusercontent.com/105966480/209473621-c5ac9568-146c-45d9-bdb3-5def3a570c84.png)

- broadcast 기능이 유용하지만, 아래와 같은 오류를 접하기 쉬움
- 이에 따라, 차후 expand기능을 활용하는게 더 적절한 경우가 많음

Note that you need to be careful before using broadcast feature.

### Failure Case

In [24]:
x = torch.FloatTensor([[[1, 2],
                        [4, 8]]])
y = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print(x.size())
print(y.size())

z = x + y

torch.Size([1, 2, 2])
torch.Size([3, 3])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2