# PyTorch AutoGrad

In [1]:
import torch

- .requires_grad_(True)
    - 직역: Gradient가 필요하니?
    - PyTorch는 Tensorflow와는 다르게 즉석에서 연산 Tree를 만들면서 추적
    - 이후, back-propagation을 진행하면서 미분 진행 중 'requires_grad_'에 따라 Gradient 적용

In [2]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]]).requires_grad_(True)

In [3]:
print(x)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [4]:
x1 = x + 2
x2 = x - 2
x3 = x1 * x2
y = x3.sum()

print(x1)
print(x2)
print(x3)
print(y)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)
tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)
tensor(14., grad_fn=<SumBackward0>)


In [5]:
y.backward()
# 현재는 backward을 requires_grad_(True)인 애들로 미분을 한다라고 이해
# y는 Scala -> Scala가 아닌 경우, Scala인 경우만 가능하다고 오류를 제시해 줌

![image](https://user-images.githubusercontent.com/105966480/210149380-6ff2dcc6-a43d-480f-b644-42107da3fd17.png)

---

$$\begin{gathered}
x=\begin{bmatrix}
x_{(1,1)} & x_{(1,2)} \\
x_{(2,1)} & x_{(2,2)}
\end{bmatrix}\\
\\
x_1=x+2 \\
x_2=x-2 \\
\\
\begin{aligned}
x_3&=x_1\times{x_2} \\
&=(x+2)(x-2) \\
&=x^2-4
\end{aligned} \\
\\
\begin{aligned}
y&=\text{sum}(x_3) \\
&=x_{3,(1,1)}+x_{3,(1,2)}+x_{3,(2,1)}+x_{3,(2,2)}
\end{aligned} \\
\\
\text{x.grad}=\begin{bmatrix}
\frac{\partial{y}}{\partial{x_{(1,1)}}} & \frac{\partial{y}}{\partial{x_{(1,2)}}} \\
\frac{\partial{y}}{\partial{x_{(2,1)}}} & \frac{\partial{y}}{\partial{x_{(2,2)}}}
\end{bmatrix} \\
\end{gathered}$$

![image](https://user-images.githubusercontent.com/105966480/210149291-23a9ff12-149c-4546-a661-c0f149b891fd.png)

- 과거에는 손으로 수식을 직접 다 풀고, 위와 같이 미분 결과가 2x가 나오면 직접 수식을 코드화해줬음
- 하지만 현재는 편하게 아래의 기능을 이용하면 쉽게 풀 수 있음
---

- .grad
    - 저장된 미분값 호출<br>
    - ![image](https://user-images.githubusercontent.com/105966480/210149291-23a9ff12-149c-4546-a661-c0f149b891fd.png)

In [6]:
print(x.grad)

tensor([[2., 4.],
        [6., 8.]])


In [7]:
print(x)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [8]:
# 2x
print(2*x)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<MulBackward0>)


---
- x3도 grad를 가지고 있음
    - 오류에 따라 '.detach().numpy()'를 붙여주면 가능함

In [9]:
print(x3.grad)

None


C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:485.)
  """Entry point for launching an IPython kernel.


In [10]:
x3.numpy()

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [14]:
x3

tensor([[-3.,  0.],
        [ 5., 12.]])

![image](https://user-images.githubusercontent.com/105966480/210150061-03f86369-8aaa-4a73-812a-c3ef353b7895.png)
- 현재 detach를 완전히 이해할 수 없음 -> 차후 다뤄볼 예정

In [13]:
x3.detach_()

tensor([[-3.,  0.],
        [ 5., 12.]])

In [11]:
x3.detach_().numpy()

array([[-3.,  0.],
       [ 5., 12.]], dtype=float32)

In [12]:
type(x3.detach_().numpy())

numpy.ndarray